language: node_js
node_js:
  - '10'

env:
  - NODE_ENV=testing

cache:
  directories:
    - "node_modules"

addons:
  postgresql: "9.4"

services:
- postgresql

before_script:
  - psql -c 'create database twine_api_test;' -U postgres
  - psql -U postgres -c "create extension postgis"

install:
  - npm install -g codecov typescript 
  - npm install
  - npm uninstall TwinePlatform/eslint-config-twine
  - npm install TwinePlatform/eslint-config-twine


script:
  - npm run lint
  - npm run cover
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always
